all: Scrabble_Game

Scrabble_Game: main.cpp Game.cpp Game.h Board.cpp Board.h Dictionary.cpp Dictionary.h Player.cpp Player.h Tilebag.cpp Tilebag.h
	g++ -o Scrabble_Game main.cpp Game.cpp Board.cpp Dictionary.cpp Player.cpp Tilebag.cpp

clean:
	rm -f Scrabble_Game
